### ISSUE TITLE
大大，这是怎么回事？我看有同样的问题，请问如何解决？

### ISSUE THREAD

**Issue by Gan1Ser** [Hellager/weibo_supertopic_sign#19]
D:\Anaconda3\envs\py37\python.exe D:/Code/weibo_supertopic_sign-main/index.py 
2022-10-22 00:05:24 INFO Start forming user cookie dict
2022-10-22 00:05:29 INFO Start get username
2022-10-22 00:05:29 INFO Start getting super topic follow list
2022-10-22 00:05:29 INFO Start forming requests params
Traceback (most recent call last):
  File "D:/Code/weibo_supertopic_sign-main/index.py", line 23, in <module>
    main_handler('', '')
  File "D:/Code/weibo_supertopic_sign-main/index.py", line 8, in main_handler
    user_follow_list = supertopic.get_follow_list(username)
  File "D:\Code\weibo_supertopic_sign-main\supertopicsign.py", line 154, in get_follow_list
    card_group = response.json().get('cards', [{}])[0].get('card_group', [])
IndexError: list index out of range

Process finished with exit code 1

**Comment by Hellager** [comment]
同样的问题指的是这里这个？https://github.com/Hellager/weibo_supertopic_sign/issues/15#issuecomment-1256974315
原因是错误流程处理没做好，具体这部分报错是为什么因为我没有复现成功所以没处理
怎么解决可以先尝试下链接里那个解决方法，因为没有反馈我也不知道之前那个方法有没有用
欢迎尝试修改并反馈效果，如果还是有问题我会及时回复并尽快解决

**Comment by Gan1Ser** [comment]
好的谢谢
