### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Josoen** [Hellager/weibo_supertopic_sign#31]
```
2023-08-03T04:07:01Z Start load request '9fc0c6ff-f871-4d0d-b8db-caaeb4430a38', version: latest
2023-08-03T04:07:01Z Finish load request '9fc0c6ff-f871-4d0d-b8db-caaeb4430a38', duration: 10.815ms, memory used: 44.168MB.
2023-08-03T04:07:01Z Start invoke request 'fb22b3da-e3de-4782-9a3a-3262c383ce48', version: latest
2023-08-03 04:07:01 INFO Start getting super topic follow list
2023-08-03 04:07:01 INFO Start forming requests params
2023-08-03 04:07:08 INFO page 1 get data success
2023-08-03 04:07:16 ERROR Traceback (most recent call last):
  File "/home/snuser/runtime/python3.6/functionmanager.py", line 404, in invoke_function
    func_response = self.instance(event, ctx)
  File "/opt/function/code/index.py", line 6, in handler
    follow_list = supertopic.get_follow_list()
  File "/opt/function/code/supertopicsign.py", line 74, in get_follow_list
    if response.json().get('errno') == -100:
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/opt/function/runtime/python3.6/rtsp/python/lib/python3.6/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return se
2023-08-03T04:07:16Z fb22b3da-e3de-4782-9a3a-3262c383ce48 ERROR function invocation exception, error: catch a 'JSONDecodeError' exception(Expecting value: line 1 column 1 (char 0))
Traceback (most recent call last):
  File "./index.py", line 6, in handler
    follow_list = supertopic.get_follow_list()
  File "./supertopicsign.py", line 74, in get_follow_list
    if response.json().get('errno') == -100:
  File "${PYTHONHOME}/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "${PYTHONHOME}/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "${PYTHONHOME}/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "${PYTHONHOME}/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-03T04:07:16Z Finish invoke request 'fb22b3da-e3de-4782-9a3a-3262c383ce48'(invoke Failed), duration: 14346.874ms, billing duration: 14347ms, memory used: 47.383MB, billing memory: 10240MB, cpu used: 0.036U
``` 

试了好几次，每次签到进度都不一样，有时能签几个就不行了，有时读取签到列表都没完成，好像是json数据解析的错误？重新抓取了一遍cookie没有效果
希望大佬看看是什么问题

**Comment by Josoen** [comment]
![1691037307123](https://github.com/Hellager/weibo_supertopic_sign/assets/55843940/fb3c6e05-0eeb-4f48-8f11-525e7a545b8a)
成功率不一定，刚发现这个问题

**Comment by Josoen** [comment]
![1691037307123](https://github.com/Hellager/weibo_supertopic_sign/assets/55843940/fb3c6e05-0eeb-4f48-8f11-525e7a545b8a)
成功率不一定，刚发现这个问题

**Comment by Hellager** [comment]
可能触发验证码了，可以本地跑一下看看具体的请求返回信息
真的是验证码的问题的话目前没什么解决办法，出现验证码的原因和账户有关
云函数用不起来又没办法自己折腾青龙面板的话，如果你是 ios 用户可以看看这个 [超话一键签到](https://weibo.com/1850606085/Mts8Kndqt)，通过捷径实现的，如果你能保证每天都会用到 PC 浏览器的话可以试 [魂签](https://github.com/inu1255/soulsign-chrome)，想用魂签但不会写脚本的话可以邮箱联系我，发一份资料给你，照着做基本也能实现，就是前期比较麻烦

**Comment by SkyeBeFreeman** [comment]
@Hellager 获取用户名的响应体长这样，然后json解析不了了。
<img width="1288" alt="image" src="https://github.com/Hellager/weibo_supertopic_sign/assets/24446200/ced1f343-c98b-4b73-ad09-564eed020976">

**Comment by CrayonsPony** [comment]
pip3 install Brotli

**Comment by CrayonsPony** [comment]
pip3 install Brotli
昨天我也出了这个问题，弄到了晚上一点多，才找到问题。
'Accept-Encoding': 'gzip, deflate, br'
这个压缩格式br的包，不会自动安装，需要手动安装一下，否则没法正确解压，就乱码了。
